### ISSUE TITLE
Enabled PuppetDB3 with API 4

### ISSUE THREAD

**Issue by HT43-bqxFqB** [sirloper/puppetdb2-rundeck#5]
The puppetdb uses a new api version 4. I fixed our local clone by using the new URIs

``` ruby
url = "#{HOST_URL}/pdb/query/v4/resources"
```

and 

``` ruby
url = "#{HOST_URL}/pdb/query/v4/facts"
```

But my ruby is not good enough to add compatibility with puppetdb 2 and 3 in code. Maybe someone could add a version check before issuing the query to puppetdb.

**Comment by sirloper** [comment]
Newest version should allow for any puppetdb version by setting the variable to your spec.
