### ISSUE TITLE
difference in certname in resources and facts

### ISSUE THREAD

**Issue by guya65** [sirloper/puppetdb2-rundeck#6]
Had an issue with a puppet db where a certname was in facts but not resources so added a nil check
This could just be a misconfigured puppet db

```
if !resources[host].nil?
    if ( name == 'serialnumber' )
        resources[host][name] = 'Serial Number ' + value
    else
        resources[host][name] = value
    end
end 
```

**Comment by kadashu** [comment]
I've met this issue and I've add a PR #7 to fix this.

**Comment by sirloper** [comment]
The fix was merged
